### PR TITLE
🐛 await core.group promises

### LINKED ISSUE #53: Unhandled promise rejection
Hrm... This doesn't look right.

https://github.com/chris-araman/CombineCloudKit/runs/3234261677?check_suite_focus=true
```
(node:892) UnhandledPromiseRejectionWarning: Error: `xcodebuild` aborted (65)
37
    at xcodebuild_xcodebuild (/Users/runner/work/_actions/mxcl/xcodebuild/v1/src/xcodebuild.ts:25:1)
38
    at process.action (internal/process/task_queues.js:93:5)
39
    at /Users/runner/work/_actions/mxcl/xcodebuild/v1/src/index.ts:135:1
40
(node:892) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
41
(node:892) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The job "succeeded". 🤔 

Investigating...

### PR DESCRIPTION
**Pull request by chris-araman**
Fixes #53.

We needed to await the `core.group` promises. Apologies for the noise. 🤦🏻‍♂️

The issue would intermittently cause `node` to exit before `xcodebuild` exited. I suspect it wasn't caught in `checks.yml` because they each run so quickly.

### CODE REVIEW

**Comment by chris-araman** [comment]
I've enabled some `eslint` rules to catch this sort of bug in the future via `npm run lint` or `npm run prepare`.

**Comment by mxcl** [comment]
Worries me we didn't realize in the PR for this one. I looked at the outputs from the tests and it seemed fine.

Need a way to catch this if it happens again for sure.

**Comment by mxcl** [comment]
Eg. this was succeeding although build/test didn't occur.

We could have allowed another project to push something broken to their main branch. Which isn't really ok.

**Comment by chris-araman** [comment]
Right. 😞

This particular type of coding error will now be caught during `npm run prepare` However, the general case isn't covered by `checks.yml`. Perhaps a post-assertion that `xcodebuild` isn't (still) running? I'd want to be sure that assertion would actually catch this case, though.

**Comment by mxcl** [comment]
The tests could add another `- run:` that tries to execute the resulting executable. If it fails then it didn't finish building.

**Comment by chris-araman** [comment]
I [tried both](https://github.com/mxcl/xcodebuild/runs/3246687208?check_suite_focus=true) based on [`v1.9.0`](https://github.com/mxcl/xcodebuild/releases/tag/v1.9.0) in the [`test`](https://github.com/mxcl/xcodebuild/tree/test) branch, but it doesn't catch the issue. `xcodebuild` is no longer running, and `my-fixture` executes just fine.

I'm not consistently seeing the `Unhandled Promise Rejection`, but I do see it [occasionally](https://github.com/mxcl/xcodebuild/runs/3246326668?check_suite_focus=true).

I think I'll try adding some slow-compiling code to the executable fixture.

**Comment by chris-araman** [comment]
I've proposed a more general solution and a check to prevent future regressions in #55.

**Pull request merged**
