### PR TITLE
Add support for visionOS

### PR DESCRIPTION
**Pull request by bamx23**
This PR adds support for running builds and tests for visionOS target.

Tested in https://github.com/kstenerud/KSCrash/pull/452

### CODE REVIEW

**Comment by bamx23** [comment]
@mxcl sory for pinging again, please take a look.
Could you run the CI jobs? Want to double check the setup.

And heads up there's goig to be a PR for `os-version` parameters that allows specifying the versions of the corrsponding OS.

**Comment by bamx23** [comment]
@mxcl here's a kind reminder

**Comment by bamx23** [comment]
@mxcl hi!

**Comment by desusai7** [comment]
@mxcl, can we please consider this ?

**Comment by mxcl** [comment]
Sorry I was busy for months and couldn't get to all the OSS requests. This looks good. I'll see why the checks didn't run

**Pull request merged**
