### PR TITLE
Add support for platform version range

### PR DESCRIPTION
**Pull request by bamx23**
Allows specifying the version (a range of versions) of the target simulator.

### CODE REVIEW

**Comment by mxcl** [comment]
I'm fixing CI currently

**Comment by mxcl** [comment]
If you rebase and rebuild the dist files it CI is working again.

**Comment by bamx23** [comment]
Thanks @mxcl, all rebased and CI passes now. Yet I'm not sure that the check I've added was run.

**Comment by mxcl** [comment]
It was not run because you did not use the matrix value `os-version` in the job.

I would also request `os-version` be renamed `platform-version` to match the `platform` key.

**Comment by bamx23** [comment]
Good catch about the use in job, fixed. And also renamed to `platform-version`.

**Pull request merged**
