### PR TITLE
Coerce parsed Swift versions

### LINKED ISSUE #29: Swift 5.4 not detected when present
Swift 5.4 was included with Xcode 12.5. I suspect this is failing because "5.4" is not "5.4.0", a valid semantic version. My workflow requests `swift: ~5.4` and `runs-on: macos-11`.

```
8
/usr/bin/mdfind kMDItemCFBundleIdentifier = com.apple.dt.Xcode
9
/Applications/Xcode_12.5.app
10
/Applications/Xcode_11.7.app
11
/Applications/Xcode_12.3.app
12
/Applications/Xcode_12.4.app
13
/Applications/Xcode_13.0.app
14
/usr/bin/mdls -raw -name kMDItemVersion /Applications/Xcode_12.5.app
15
and]/usr/bin/mdls -raw -name kMDItemVersion /Applications/Xcode_11.7.app
16
and]/usr/bin/mdls -raw -name kMDItemVersion /Applications/Xcode_12.3.app
17
and]/usr/bin/mdls -raw -name kMDItemVersion /Applications/Xcode_12.4.app
18
and]/usr/bin/mdls -raw -name kMDItemVersion /Applications/Xcode_13.0.app
19
and]/usr/bin/swift --version
20
/usr/bin/swift --version
21
/usr/bin/swift --version
22
/usr/bin/swift --version
23
/usr/bin/swift --version
24
2021-06-17 17:08:01.601 xcodebuild[1266:23832] [MT] DVTPlugInManager: Required plug-in compatibility UUID 42E1F17B-27B3-4DE8-92A8-DC76BA4F5921 for DVTCoreGlyphs.framework (com.apple.dt.DVTCoreGlyphs) not present
25
2021-06-17 17:08:01.601 xcodebuild[1266:23832] [MT] DVTPlugInManager: Required plug-in compatibility UUID 42E1F17B-27B3-4DE8-92A8-DC76BA4F5921 for DVTCoreGlyphs.framework (com.apple.dt.DVTCoreGlyphs) not present
26
Apple Swift version 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53)
27
Target: x86_64-apple-darwin20.5.0
28
2021-06-17 17:08:06.416 xcodebuild[1570:25368] [MT] DVTPlugInManager: Required plug-in compatibility UUID 42E1F17B-27B3-4DE8-92A8-DC76BA4F5921 for DVTCoreGlyphs.framework (com.apple.dt.DVTCoreGlyphs) not present
29
2021-06-17 17:08:06.416 xcodebuild[1570:25368] [MT] DVTPlugInManager: Required plug-in compatibility UUID 42E1F17B-27B3-4DE8-92A8-DC76BA4F5921 for DVTCoreGlyphs.framework (com.apple.dt.DVTCoreGlyphs) not present
30
Apple Swift version 5.4 (swiftlang-1205.0.26.9 clang-1205.0.19.55)
31
Target: x86_64-apple-darwin20.5.0
32
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
33
Target: x86_64-apple-darwin20.5.0
34
Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)
35
Target: x86_64-apple-darwin20.5.0
36
swift-driver version: 1.26 Apple Swift version 5.5 (swiftlang-1300.0.19.104 clang-1300.0.18.4)
37
Target: x86_64-apple-macosx11.0
38
Error: Error: No Xcode with Swift ~> ~5.4
39
swift-driver version: 1.26 
```

### PR DESCRIPTION
**Pull request by chris-araman**
Fixes #29.

### CODE REVIEW

**Comment by mxcl** [comment]
K, so we have worse problems since the test fails, but CI passes:

https://github.com/mxcl/xcodebuild/pull/30/checks?check_run_id=2852362573

Also, it is failing after applying your patch…

**Comment by chris-araman** [comment]
It's failing because 5.4 isn't available on `macos-10.15`, which is still `masos-latest`. Xcode 12.5 and 13 beta, and Swift 5.4 and 5.5 are currently only available on `macos-11`, which is currently in [private preview](https://github.com/actions/virtual-environments/issues/2486).

**Comment by mxcl** [comment]
oof. I'm an idiot. K, I'll merge and trust that it works. Thanks!

**Comment by chris-araman** [comment]
No worries. 😊 I'm happy to add CI tests, but I don't think they'd run without access to `macOS-11`.

**Pull request merged**
