### PR TITLE
Emit swift-driver version as info, not warning

### PR DESCRIPTION
**Pull request by chris-araman**
It seems reasonable to assume that most of the time `stderr` output could be interesting. However, in this case, it very much is not.

```
caraman@mac ~> swift --version
swift-driver version: 1.26.9 Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)
Target: arm64-apple-macosx12.0
caraman@mac ~> swift --version 2> /dev/null
Apple Swift version 5.5.1 (swiftlang-1300.0.31.4 clang-1300.0.29.6)
Target: arm64-apple-macosx12.0
```

### CODE REVIEW

**Comment by mxcl** [comment]
I don't think we should silence it. In the previous version I used `info` instead, probably for the reason you state here.

**Comment by chris-araman** [comment]
Oh, sure. That seems fine. Just switch between `info` and `warning` instead?

**Comment by chris-araman** [comment]
There. Is that more what you had in mind? Or would you prefer I revert back to `core.info` only? I was hoping to err on the side of caution; that unexpected output to `stderr` is generally worth human review.

**Comment by mxcl** [comment]
Yeah cool. Merge and release please!

**Review by mxcl — APPROVED** [review]

**Pull request merged**
